# Generated by Django 3.2.16 on 2023-07-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attendance_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
    ]
