# Generated by Django 3.2.10 on 2023-07-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230716_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
